[build]
  command = "npm run build"
  publish = "dist"

 [build.environment]
   NODE_VERSION = "20"

# Proxy API to backend (browser requests stay same-origin over HTTPS)
[[redirects]]
  from = "/api/*"
  to = "http://im.rainplay.cn:52483/api/:splat"
  status = 200

# SPA fallback so client-side routes work
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
